"""add is_active to courses

Revision ID: d4225c7d1629
Revises: 1aa4a7da4fec
Create Date: 2026-05-02 13:54:13.139243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4225c7d1629'
down_revision: Union[str, None] = '1aa4a7da4fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_active')
    # ### end Alembic commands ###
